In [1]:
languages = ['Java' , 'Python' , 'Javascript']
versions = [14,3,6]
result = zip(languages,versions)
print(list(result))

[('Java', 14), ('Python', 3), ('Javascript', 6)]


In [2]:
data = {'Name' :['tom','nick','krish','jack'], 'Age':[20,21,19,18]}
import pandas as pd
dfEmpl = pd.DataFrame(data)
print(dfEmpl)

    Name  Age
0    tom   20
1   nick   21
2  krish   19
3   jack   18


In [4]:
seremplage = pd.Series(dfEmpl['Age'])
seremplage.head(3)


0    20
1    21
2    19
Name: Age, dtype: int64

In [1]:
import numpy as np
array1= np.array ([1,3,5])
print("np.array():\n", array1)

np.array():
 [1 3 5]


In [2]:
array2= np.zeros((3,3))
print("\nnp.zeros():\n", array2)


np.zeros():
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
array3= np.array([1,3,5,7,9,11])
array4= np.reshape(array3,(2,3))
array5= np.transpose(array4)
print("Original array:\n", array3)
print("Reshaped array:\n", array4)
print("Transposed array:\n", array5)

Original array:
 [ 1  3  5  7  9 11]
Reshaped array:
 [[ 1  3  5]
 [ 7  9 11]]
Transposed array:
 [[ 1  7]
 [ 3  9]
 [ 5 11]]
